configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NzRhM2MwNGI0Y2ZhYTBjM2E4ZWYwYzMzZTBlZTcyZGU1ZDU0MzZhMDBlYzIwOTA5OGFkNDcxYjEwOGUzZGExMGRhNDAxMDk3YTJlOWZiMDAyYjhlNTkyNzk3YjhlMTAxMjQ2ODE5ZmJkNjM3MjJhNDRkY2Q4ZTNjMmRiMDk0NmI=
